targetInstance: ${TEST_URL:http://localhost:8096}

spring:
  cache:
    cache-names: legalRepTokenCache, legalRepOrgDeletedTokenCache, legalRepOrgSuccessTokenCache, citizenTokenCache
    caffeine:
      spec: expireAfterAccess=3600s
