server:
  port: 8096

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Welcome to Case Payment Service
  main:
    allow-bean-definition-overriding: true
  jackson.date-format: yyyy-MM-dd
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_URL:http://127.0.0.1:5000}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:ia}
            client-secret: ${IA_IDAM_SECRET:something}
      resourceserver:
        jwt:
          jwk-set-uri: ${IDAM_URL:http://127.0.0.1:5000}/o/jwks


idam:
  baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:ia}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:iac}

fees-register:
  api:
    url: ${FEES_REGISTER_API_URL:http://localhost:8991}
  fees:
    feeWithHearing:
      channel: default
      event: issue
      jurisdiction1: tribunal
      jurisdiction2: immigration and asylum chamber
      keyword: ABC
      service: other
    feeWithoutHearing:
      channel: default
      event: issue
      jurisdiction1: tribunal
      jurisdiction2: immigration and asylum chamber
      keyword: DEF
      service: other

rd-professional:
  api:
    url: ${PROF_REF_DATA_URL:http://localhost:8991}

payment:
  api:
    url: ${PAYMENT_API_URL:http://localhost:8991}
  params:
    organisationUrn: immigration and asylum chamber
    siteId: ABA3

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
    - "/csrf"
    - "/testing-support/**"
  roleEventAccess:
    caseworker-ia-legalrep-solicitor:
    - "startAppeal"
    - "editAppeal"
    - "paymentAppeal"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
auth.idam.client.detailsUri: "/details"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:ia}
auth.idam.client.secret: ${IA_IDAM_SECRET:something}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:http://localhost}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:something}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}
