server:
  port: 8096

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

  health:
    probes:
      enabled: true

spring:
  application:
    name: Welcome to Case Payment Service
  main:
    allow-bean-definition-overriding: true
  jackson.date-format: yyyy-MM-dd
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}/o
        registration:
          oidc:
            client-id: ${IA_IDAM_CLIENT_ID:iac}
            client-secret: ${IA_IDAM_SECRET:NDPH6DFQBIPA9UP7}
      resourceserver:
        jwt:
          jwk-set-uri: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}/o/jwks


idam:
  baseUrl: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:https://ia-case-api-aat.service.core-compute-aat.internal/oauth2/callback}
  system:
    username: ${IA_SYSTEM_USERNAME:ia-system-user@fake.hmcts.net}
    password: ${IA_SYSTEM_PASSWORD:something}
  scope: "openid profile authorities acr roles create-user manage-user search-user"
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IA_S2S_MICROSERVICE:iac}
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:iac}

fees-register:
  api:
    url: ${FEES_REGISTER_API_URL:http://localhost:8991}
  fees:
    feeWithHearing:
      channel: default
      event: issue
      jurisdiction1: tribunal
      jurisdiction2: immigration and asylum chamber
      keyword: HearingOral
      service: other
    feeWithoutHearing:
      channel: default
      event: issue
      jurisdiction1: tribunal
      jurisdiction2: immigration and asylum chamber
      keyword: HearingPaper
      service: other

rd-professional:
  api:
    url: ${PROF_REF_DATA_URL:http://localhost:8991}

payment:
  api:
    url: ${PAYMENT_API_URL:http://localhost:8991}
  params:
    organisationUrn: immigration and asylum chamber
    siteId: BFA1

core-case-data:
  api:
    url: ${CCD_URL:http://127.0.0.1:4452}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v3/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
    - "/csrf"
    - "/testing-support/**"
    - "/payment-updates"
  roleEventAccess:
    citizen:
    - "startAppeal"
    - "editAppeal"
    - "paymentAppeal"
    caseworker-ia-legalrep-solicitor:
    - "startAppeal"
    - "editAppeal"
    - "paymentAppeal"
    - "payAndSubmitAppeal"
    - "payForAppeal"
    caseworker-ia-admofficer:
    - "recordRemissionDecision"
    caseworker-ia-system:
    - "updatePaymentStatus"

### dependency configuration
auth.idam.client.baseUrl: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
auth.idam.client.detailsUri: "/details"
auth.idam.client.id: ${IA_IDAM_CLIENT_ID:iac}
auth.idam.client.secret: ${IA_IDAM_SECRET:NDPH6DFQBIPA9UP7}
auth.idam.client.redirectUri: ${IA_IDAM_REDIRECT_URI:https://ia-case-api-aat.service.core-compute-aat.internal/oauth2/callback}
auth.provider.service.client.baseUrl: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:iac}
idam.s2s-auth.url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
