idam:
  s2s-authorised:
    services: ia,payment_app

app:
  cache:
    enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.cache.autoconfigure.CacheAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.RedisRepositoriesAutoConfiguration
